# Generated by Django 2.1.3 on 2018-11-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0002_auto_20181116_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('PBL', 'Pawn Brokers License'), ('GST', 'Goods & Service Tax')], default='PBL', max_length=30),
        ),
    ]
