# Generated by Django 2.1.3 on 2018-11-20 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0003_auto_20181117_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Customer'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='itemtype',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('O', 'Other')], default='Gold', max_length=30),
        ),
        migrations.AlterField(
            model_name='release',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release', to='girvi.Loan'),
        ),
    ]
