# Generated by Django 2.1.3 on 2018-11-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0004_auto_20181120_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='itemvalue',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
