# Generated by Django 2.1.3 on 2018-11-16 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chitfund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 11, 36, 31, 672541)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='date_collected',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 11, 36, 31, 656916)),
        ),
    ]
