# Generated by Django 2.1.3 on 2018-11-16 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chitfund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 12, 50, 42, 800503)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='date_collected',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 12, 50, 42, 800503)),
        ),
    ]
