# Generated by Django 2.1.3 on 2018-11-16 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chitfund', '0002_auto_20181116_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 12, 51, 10, 361791)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='date_collected',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 12, 51, 10, 361791)),
        ),
    ]
