# Generated by Django 2.1.3 on 2018-11-16 04:26

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('phonenumber', models.CharField(max_length=20)),
                ('Address', models.TextField(max_length=100)),
                ('type', models.CharField(max_length=30)),
                ('relatedas', models.CharField(max_length=30)),
                ('relatedto', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('organisation', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=30)),
                ('initial', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
