# Generated by Django 2.1.3 on 2018-11-16 07:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
