# Generated by Django 2.1.3 on 2018-11-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20181120_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/customer/pic/'),
        ),
    ]
