# Generated by Django 2.1.3 on 2018-11-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_customer_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/supplier/pic/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
