# Generated by Django 2.1.3 on 2018-11-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='is_return',
            field=models.CharField(max_length=30, verbose_name='Return'),
        ),
    ]
