# Generated by Django 2.1.3 on 2018-11-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20181120_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='makingcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='is_return',
            field=models.BooleanField(default=False, verbose_name='Return'),
        ),
    ]
