# Generated by Django 2.1.3 on 2018-11-22 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20181121_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balancetype',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Metal', 'Metal')], default='Cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymenttype',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=30),
        ),
    ]
